#!/usr/bin/env node

import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repository = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const registryRelativePath = 'fixtures/generation/registry-v1.json';
const registryPath = path.join(repository, registryRelativePath);
const registryBytes = readFileSync(registryPath);
const registry = JSON.parse(registryBytes.toString('utf8'));
const mode = process.argv[2] ?? '--check';

if (!['--check', '--write'].includes(mode) || process.argv.length > 3) {
  throw new Error('usage: node fixtures/generation/generate.mjs [--check|--write]');
}

const assert = (condition, message) => {
  if (!condition) throw new Error(message);
};
const sha256 = (bytes) => createHash('sha256').update(bytes).digest('hex');
const pretty = (value) => `${JSON.stringify(value, null, 2)}\n`;
const resolveRepositoryPath = (relativePath) => {
  assert(!path.isAbsolute(relativePath), `absolute artifact path: ${relativePath}`);
  const resolved = path.resolve(repository, relativePath);
  assert(resolved.startsWith(`${repository}${path.sep}`), `artifact path escapes: ${relativePath}`);
  return resolved;
};
const hex64 = (value) => `0x${value.toString(16).padStart(16, '0')}`;

const MASK_64 = (1n << 64n) - 1n;
const GAMMA = 0x9e3779b97f4a7c15n;
const MULTIPLIER_1 = 0xbf58476d1ce4e5b9n;
const MULTIPLIER_2 = 0x94d049bb133111ebn;

const splitMix64Sequence = (seed, count) => {
  let state = seed;
  const outputs = [];
  for (let index = 0; index < count; index += 1) {
    state = (state + GAMMA) & MASK_64;
    let mixed = state;
    mixed = ((mixed ^ (mixed >> 30n)) * MULTIPLIER_1) & MASK_64;
    mixed = ((mixed ^ (mixed >> 27n)) * MULTIPLIER_2) & MASK_64;
    mixed = (mixed ^ (mixed >> 31n)) & MASK_64;
    outputs.push(hex64(mixed));
  }
  return outputs;
};

assert(registry.registry_schema === 'helix.fixture-generator-registry/1', 'registry mismatch');
const vectorGenerator = registry.generators.find(({ id }) => id === 'toolchain.splitmix64-vectors');
assert(vectorGenerator, 'seeded vector generator absent');
assert(vectorGenerator.algorithm === 'helix.splitmix64-fixed-gamma/1', 'PRNG mismatch');
assert(/^0x[0-9a-f]{16}$/.test(vectorGenerator.seed), 'seed format mismatch');
const vectorArtifact = vectorGenerator.artifacts[0];
const vector = {
  vector_schema: 'helix.prng-vector/1',
  algorithm: vectorGenerator.algorithm,
  seed: vectorGenerator.seed,
  word_bits: 64,
  count: 16,
  outputs: splitMix64Sequence(BigInt(vectorGenerator.seed), 16),
};
const vectorText = pretty(vector);
const generatedArtifacts = new Map([[vectorArtifact.path, Buffer.from(vectorText)]]);

const report = {
  generation_report_schema: 'helix.fixture-generation-report/1',
  registry: {
    path: registryRelativePath,
    bytes: registryBytes.length,
    sha256: sha256(registryBytes),
  },
  generators: registry.generators.map((generator) => ({
    id: generator.id,
    version: generator.version,
    randomness: generator.randomness,
    seed: generator.seed,
    algorithm: generator.algorithm,
    artifacts: generator.artifacts.map((artifact) => {
      const bytes =
        generatedArtifacts.get(artifact.path) ?? readFileSync(resolveRepositoryPath(artifact.path));
      return {
        path: artifact.path,
        format: artifact.format,
        schema_path: artifact.schema_path,
        bytes: bytes.length,
        sha256: sha256(bytes),
      };
    }),
  })),
  verdict: 'pass',
};
const reportText = pretty(report);

const reconcile = (relativePath, expected) => {
  const artifactPath = resolveRepositoryPath(relativePath);
  if (mode === '--write') {
    mkdirSync(path.dirname(artifactPath), { recursive: true });
    writeFileSync(artifactPath, expected);
    return;
  }
  assert(existsSync(artifactPath), `${relativePath}: generated artifact absent`);
  const actual = readFileSync(artifactPath, 'utf8');
  assert(actual === expected, `${relativePath}: generated bytes drifted; run fixtures:generate`);
};

reconcile(vectorArtifact.path, vectorText);
reconcile(registry.report.path, reportText);

console.log(
  `PASS deterministic generation: ${registry.generators.length} generators, ${report.generators.flatMap(({ artifacts }) => artifacts).length} authority artifacts, 1 committed seed`,
);
console.log(`PASS SplitMix64 vector: ${vector.count} outputs from ${vector.seed}`);
console.log(`PASS generation report: ${Buffer.byteLength(reportText)} bytes`);
