#!/usr/bin/env node
import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';import {readFileSync,statSync} from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
const dir=path.dirname(fileURLToPath(import.meta.url));const root=path.resolve(dir,'../../..');const manifest=JSON.parse(readFileSync(path.join(dir,'manifest.json')));const arg=process.argv[2];const assert=(v,m)=>{if(!v)throw new Error(m)};const same=(a,b,m)=>assert(JSON.stringify(a)===JSON.stringify(b),`${m} mismatch`);const sha=b=>createHash('sha256').update(b).digest('hex');const git=a=>execFileSync('git',a,{cwd:root,maxBuffer:128*1024*1024});const text=a=>git(a).toString();const show=f=>git(['show',`${manifest.commit}:${f}`]);const showText=f=>show(f).toString();const showJson=f=>JSON.parse(showText(f));
assert(arg,'usage: node evidence/phase-04/P04-011/verify.mjs <commit>');assert(/^[0-9a-f]{40}$/.test(arg),'full commit');assert(arg===manifest.commit,'manifest commit');assert(manifest.schema_version===1&&manifest.task_id==='P04-011'&&manifest.verdict==='pass','verdict');same(manifest.requirements,['CORE-001','CORE-003','INV-004','INV-007','PLAT-001','QUAL-001','SEC-001','SEC-002'],'requirements');same(manifest.accepted_adrs,['0013'],'ADRs');assert(text(['rev-parse',`${arg}^{commit}`]).trim()===arg,'commit');assert(text(['rev-parse',`${arg}^`]).trim()===manifest.base_commit,'parent');assert(text(['rev-parse',`${arg}^{tree}`]).trim()===manifest.source_tree,'tree');const changes=text(['diff-tree','--no-commit-id','--name-only','-r',arg]).trim().split('\n');assert(changes.length===manifest.verification.source_artifacts,'artifact count');assert(sha(git(['diff','--binary',manifest.base_commit,arg]))===manifest.diff_sha256,'diff hash');
const verifier=readFileSync(fileURLToPath(import.meta.url));assert(statSync(fileURLToPath(import.meta.url)).size===manifest.verifier.bytes,'verifier bytes');assert(sha(verifier)===manifest.verifier.sha256,'verifier hash');for(const a of manifest.authorities){const b=show(a.path);assert(b.length===a.bytes,`${a.path}: bytes`);assert(sha(b)===a.sha256,`${a.path}: hash`)}
const p=showJson('docs/architecture/native-host-skeleton-v1.json');assert(p.schema==='helix.native-host-skeleton/1'&&p.plan_item==='P04-011','policy');assert(p.runtime.crate==='wasmtime'&&p.runtime.version==='46.0.1'&&!p.runtime.default_features,'runtime');same(p.runtime.features,['async','component-model','component-model-async','cranelift','runtime','std'],'features');assert(!p.runtime.wasi_adapters_installed,'WASI');assert(p.capabilities.length===11&&new Set(p.capabilities).size===11,'capabilities');assert(Object.values(p.allowlist).every(Boolean),'allowlist');assert(Object.values(p.engine).every(Boolean),'engine');assert(p.validation.native_host_mutation_canaries===41&&p.validation.dependency_mutation_canaries===13,'canaries');for(const k of ['abi_calls_linked','component_instantiation_present','filesystem_present','durability_present','network_present','entropy_present','gpu_execution_present','database_functionality_added'])assert(p.claim_boundary[k]===false,`${k} claim`);
const source=showText('crates/helix-host-native/src/lib.rs');for(const m of ['pub enum NativeCapability {','pub struct CapabilityPolicy {','pub struct NativeHost {','config.wasm_component_model(true);','config.consume_fuel(true);','config.epoch_interruption(true);','Component::new(&self.engine, bytes)'])assert(source.includes(m),`source ${m}`);for(const m of ['wasmtime_wasi','std::fs','std::net','getrandom','unsafe {'])assert(!source.includes(m),`ambient ${m}`);
const dependency=showJson('tests/toolchain/dependency-policy.json').rust;assert(dependency.external_packages.length===121,'external packages');assert(dependency.license_text_exceptions.length===14,'license exceptions');const wasmtime=dependency.direct_dependencies.find(v=>v.name==='wasmtime');assert(wasmtime&&wasmtime.version_requirement==='=46.0.1'&&!wasmtime.default_features,'direct Wasmtime');same(wasmtime.features,p.runtime.features,'Wasmtime features');const licenses=showJson('.github/ci/rust-license-inventory.json');assert(licenses.packages.length===121,'license packages');assert(licenses.packages.reduce((n,v)=>n+v.license_files.length,0)===204,'license files');
const cargo=showText('Cargo.toml');const matrix=showJson('.github/ci/matrix.json');const workflow=showText('.github/workflows/ci.yml');assert(cargo.includes('plan-item = "P04-011"')&&cargo.includes('status = "native-host-skeleton-v1"'),'maturity');assert(matrix.plan_items.at(-1)==='P04-011','CI history');assert(workflow.includes('corepack npm run host:native:check')&&workflow.includes('corepack npm run host:native:test'),'hosted gates');const check=execFileSync('node',['tests/toolchain/check-native-host-skeleton.mjs'],{cwd:root,encoding:'utf8'});assert(check.includes('Wasmtime 46.0.1'),'live check');const canaries=execFileSync('node',['tests/toolchain/test-native-host-skeleton.mjs'],{cwd:root,encoding:'utf8'});assert(canaries.includes('41 mutations rejected'),'live canaries');
process.stdout.write('PASS P04-011 source: 44 artifacts add the native Wasmtime skeleton\nPASS P04-011 runtime: exact 46.0.1 async Component Model without WASI adapters\nPASS P04-011 grants: 11 bounded exact capability kinds deny by default\nPASS P04-011 dependencies: 121 exact crates, 204 license files, 14 exceptions\nPASS P04-011 boundary: no linked ABI, ambient platform, GPU, or database claim\n');
